### ISSUE TITLE
No anda cdpedia.exe en windows XP

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/cdpedia#102]
```
Al correr cdpedia.exe aparece la imágen de splash por algunos segundos, y 
luego el proceso se cierra. 

No lanza ningún error ni en la consola.

Sistema:
 * WinXP SP3 32 bits
 * Instalado Python 2.5. Me late que el problema pude venir por aca.

```

Original issue reported on code.google.com by `gringotu...@gmail.com` on 9 Apr 2011 at 2:56

**Comment by GoogleCodeExporter** [comment]
```
cdpedia.exe estaba siendo generado con Python 2.6, que requiere una .dll que no 
incluíamos en el disco.

Esto fue solucionado volviendo a Python 2.5 para la generación del .exe.
```

Original comment by `alecura` on 4 May 2011 at 1:48
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
```
Le doy doble clik a cdpedia.exe aparece la imágen de splash por algunos 
segundos, y luego se cierra. No pasa nada.
Debo bajar algun programa que le falta?
He probado en varias PC y siempre igual.
Gracias
```

Original comment by `gigapepe...@gmail.com` on 26 Sep 2011 at 4:24

**Comment by GoogleCodeExporter** [comment]
```
Hola, en qué versión de Windows lo estas corriendo?

¿Podrias adjuntar el archivo cdpedia.log? Deberia generarse en el directorio 
del usuario de windows, por ejemplo, C:\Documents and 
Settings\usuario\cdpedia.log
```

Original comment by `gringotu...@gmail.com` on 26 Sep 2011 at 4:35

**Comment by GoogleCodeExporter** [comment]
Original comment by `dmascialino` on 29 Sep 2011 at 3:41

**Comment by GoogleCodeExporter** [comment]
```
Buenos días,

Continúo con el problema que no puedo hacer correr CDPedia en una netbook 
Hewlett Packard HP Mini 210-100 Procesador Inter Atom N450 1.66 Ghz - Ram 2 GB 
- SO 32 bits que no cuenta con lector de DVD ni de CD.

Copié todo el contenido del CDPedia en el disco duro a través de mi memoria 
USB,
pero cuando hago clic en CDPedia.exe se abre el logo de cdpedia (imagen de 
splash por algunos segundos) y no funciona.  

El error que reporta el archivo cdpedia.log es que no está instalado el 
archivo SuffixTree y que baje de la sgte.dirección:
  http://www.deeplayer.com/claudio/misc/SuffixTree-0.7.1-8bit.tar.bz2

Ingresé a esa dirección y bajé el archivo: SuffixTree-0.7.1-8bit.tar.bz2 el 
cual lo descomprí y generó la carpeta: SuffixTree-0.7.1 con otras 
sub-carpetas y varios archivos que según entiendo están con extensiones de 
Pyton.

Ahora bien no se cómo continuar porque no encuentro ningún archivo setup o 
install de instalación.

De todas formas adjunto el log e igualmente copio a continuación lo que dice 
dicho archivo.
Muchas gracias por la cooperación.
Atte,
Raúl Magne.

Favor responder a raumagtor@gmail.com 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++  este es el log

WARNING: SuffixTree no está instalado!!
La generación de la matriz de similitud de términos puede ser LENTA.
Lo mejor es instalarlo de aquí (lo bajás, setup.py build, install):
  http://www.deeplayer.com/claudio/misc/SuffixTree-0.7.1-8bit.tar.bz2
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\pyinstaller\iu.py", line 436, in importHook
  File "C:\pyinstaller\iu.py", line 521, in doimport
  File ".\cdpedia.py", line 26, in <module>
    from src.armado import server
  File "C:\pyinstaller\iu.py", line 477, in importHook
  File "C:\pyinstaller\iu.py", line 521, in doimport
  File "cdpedia\src\armado\server.py", line 192, in <module>
    class WikiHTTPRequestHandler(BaseHTTPRequestHandler):
  File "cdpedia\src\armado\server.py", line 197, in WikiHTTPRequestHandler
    _art_mngr = compresor.ArticleManager()
  File "cdpedia\src\armado\compresor.py", line 48, in __init__
    self.num_bloques = int(open(fname).read().strip())
IOError: [Errno 2] No such file or directory: 'cdpedia/bloques\\numbloques.txt'
```

Original comment by `raumag...@gmail.com` on 27 Oct 2012 at 2:16

**Comment by GoogleCodeExporter** [comment]
```
Hola Raul.

Me parece que el problema pasa por otro lado, y no tanto porque estés en 
Windows, pero necesito más info para acotarlo, te agradecería respondas las 
siguientes preguntas:

- ¿En qué directorio copiaste toda la CDPedia?

- Abajo de ese directorio, ¿tenés un directorio llamado "cdpedia"? Si sí, 
adentro de este último hay uno llamado "bloques"? Podrías listar este 
directorio?

Gracias, slds.
```

Original comment by `facundob...@gmail.com` on 4 Nov 2012 at 2:57
