### ISSUE TITLE
missing py2exe dependencies for third party libraries 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/cdpedia#143]
```
What steps will reproduce the problem?
1. create a cdpedia iso from trunk
2. try to start it on windows
3. it will never start

In the logs, this is shown:

Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\pyinstaller\iu.py", line 436, in importHook
  File "C:\pyinstaller\iu.py", line 521, in doimport
  File ".\cdpedia.py", line 50, in <module>
    from werkzeug.serving import ThreadedWSGIServer
  File "C:\pyinstaller\iu.py", line 436, in importHook
  File "C:\pyinstaller\iu.py", line 521, in doimport
  File "cdpedia\src\third_party\werkzeug\serving.py", line 50, in <module>
    from werkzeug._internal import _log
  File "C:\pyinstaller\iu.py", line 436, in importHook
  File "C:\pyinstaller\iu.py", line 521, in doimport
  File "cdpedia\src\third_party\werkzeug\_internal.py", line 12, in <module>
    from weakref import WeakKeyDictionary
  File "C:\pyinstaller\iu.py", line 455, in importHook
ImportError: No module named weakref

```

Original issue reported on code.google.com by `alecura` on 13 Aug 2012 at 10:38

**Comment by GoogleCodeExporter** [comment]
```
Al margen de que despues se mejore algo registro el estado actual de la 
construccion del exe

Exe(s) construido a partir del minidump que hizo Facundo [0]; por las fechas y 
lo que se lee  corresponderia a  
~cdpedistas/cdpedia/trunk r389 ; ademas esta puesto manualmente el diff en 
compresor.py que soluciona el problema de encoding [1][2]

Receta usada para obtener el exe (attached cdpedia_r389+.py el cdpedia.py 
usado):
    0. obtener un minidump
    1. copiar los contenidos a d:\tmp\cd_mini_3
    2. obtener pyinstaller 2.0
    3. descomprimirlo (sin instalar) a D:\tmp\pyinstaller-2.0
    4. tener un python 2.7.3 con solamente pywin32 v 2.17 instalado, lo requiere pyinstaller, yo instale desde pywin32-217.win32-py2.7.exe
    5. agregar un cdpedia.pth a site-packages con la linea:
       D:\tmp\cd_mini_3\cdpedia\src\third_party
    6. modificado cdpedia.py para permitir ver stdout en la consola si existe un file 'debug' al mismo nivel que cdpedia.py , esto facilita ver cuando la carga de una pagina produce errores
    7. Agregados imports para cada paquete en third_party, de modo que pyinstaller capture las dependencias
    8. Agregados imports que pyinstaller no alcanzaba a detectar
    9. Debug build: genera una applicacion de consola. Se genera con
         d:
     cd D:\tmp\pyinstaller-2.0
     c:\python27\python.exe pyinstaller.py  --onefile D:\tmp\cd_mini_3\cdpedia.py

       El exe resultante quea en D:\tmp\pyinstaller-2.0\cdpedia\dist
       El archivo con los warnings del build es:
          D:\tmp\pyinstaller-2.0\cdpedia\build\pyi.win32\cdpedia\warncdpedia.txt
    10. Prueba manual del debug exe:
    a. copiar el exe a donde teniamos los contenidos del mini iso; crear un archivo 'debug' en el mismo directorio (habilita print a consola)
    b. abrir otra consola en ese directorio y arrancar desde la consola cdpedia.exe
    c. navegar, bien usando el boton de pagina random o picando links; mirar la consola en cada paso para ver si saltan problemas
   11. Release build:
    Como en debug pero la linea de comandos para construir el exe es ahora
        c:\python27\python.exe pyinstaller.py  --onefile --noconsole D:\tmp\cd_mini_3\cdpedia.py

Observacion: en este tipo de build el exe debe ser regenerado cada vez que 
cualquier .py cambia

Adjuntado cdpedia_console.r389+.exe.zip con el debug exe ; el release lo 
adjunto en el siguiente comentario por limitaciones de google.          

[0] mini iso thread 
http://groups.google.com/group/cdpedia/browse_thread/thread/22c82b1a729aae81

[1] encoding issue 
http://code.google.com/p/cdpedia/issues/detail?id=144&can=1&start=100

[2] encoding thread 
http://groups.google.com/group/cdpedia/browse_thread/thread/d547a396945c7973


```

Original comment by `ccanepacc@gmail.com` on 2 Oct 2012 at 2:32

Attachments:
- [cdpedia_r389+.py](https://storage.googleapis.com/google-code-attachments/cdpedia/issue-143/comment-1/cdpedia_r389+.py)
- [cdpedia_console.r389+.exe.zip](https://storage.googleapis.com/google-code-attachments/cdpedia/issue-143/comment-1/cdpedia_console.r389+.exe.zip)

**Comment by GoogleCodeExporter** [comment]
```
Aqui attacheado el build release
```

Original comment by `ccanepacc@gmail.com` on 2 Oct 2012 at 2:35

Attachments:
- [cdpedia.r389+.exe.zip](https://storage.googleapis.com/google-code-attachments/cdpedia/issue-143/comment-2/cdpedia.r389+.exe.zip)

**Comment by GoogleCodeExporter** [comment]
```
Hola ccanepacc, por qué tomaste la decisión de meter todo cdpedia en el .exe 
en vez de hacer el método del lanzador?

Lo que proponiamos con el lanzador es no tener que generar el .exe cuando 
cambia el código de cdpedia. El principal problema que siempre tenemos es que 
agregamos cada tanto algo de stdlib, por eso una propuesta era agregar una 
parte razonable de la stdlib al .exe
```

Original comment by `gringotu...@gmail.com` on 2 Oct 2012 at 3:08

**Comment by GoogleCodeExporter** [comment]
```
Un testeo parcial usando un crawler y el exe construido en paso anterior

Puesto que no estamos totalmente seguros de que pyinstaller haya capturado 
todos los modulos necesarios, y por otro lado puede haber algunos bugs no 
relacionados a pyinstaller, la idea es poner a un crawler a capturar el sitio 
que levanta cdpedia.py y ver que errores se producen.

Para eso cambié un par try / except en web_app.py que impidian que los errores 
pasen al log / consola. Archivo adjuntado como web_app_r389+_test.py

(idealmente algo del estilo deberia llegar a trunk, es util al margen de en que 
OS se hacen pruebas)

Despues lancé el exe (dejando que los mensajes vayan al cdpedia.log)
Y lancé un crawler (guardasitios o como quieran llamarle).
Aqui en windows xp usé WinHTTrack Website Copier 3.44-1

Los unicos settings que le metí fueron:
    target url: http://localhost:8000
    ignore : dominios que empiezan con 'es.'
Para el minidump que nos estamos refiriendo tardó aprox 1 hora y 10 minutos; 
posiblemente se pueda configurar de modo que sea mas rapido.

Los resultados que interesan son el cdpedia.log y posiblemente el log paralelo 
del crawler.

En el cdpedia.log quedaron tracebacks (buscar 'traceb') y algunos 404 
sospechosos porque el target está en static/ ; no miré que otra info 
interesante se puede sacar de alli.

Otra cosa a mirar es que mientras el crawler trabajaba e iba poniendo info 
acerca de los links y paginas salian muchos links hacia 'common.wikimedia.org'. 
No sé si esos links deberian estar así o si deberian haber sido cambiados 
hacia algun recurso local. ( buscar en el log del crawler por 'commons' o 
'forbiden'para ver ejemplos)

No analicé nada todavia, registro los resultados para no perderlos y para que 
otros puedan echar un vistazo.

Attached los logs y el web_app modificado.

```

Original comment by `ccanepacc@gmail.com` on 2 Oct 2012 at 4:39

Attachments:
- [web_app.py](https://storage.googleapis.com/google-code-attachments/cdpedia/issue-143/comment-4/web_app.py)
- [cdpedia.under_crawler.log](https://storage.googleapis.com/google-code-attachments/cdpedia/issue-143/comment-4/cdpedia.under_crawler.log)
- [crawler.log](https://storage.googleapis.com/google-code-attachments/cdpedia/issue-143/comment-4/crawler.log)

**Comment by GoogleCodeExporter** [comment]
Original comment by `gringotu...@gmail.com` on 2 Oct 2012 at 7:51
- Added labels: **Milestone-0.7.1**

**Comment by GoogleCodeExporter** [comment]
```
Esto ya lo solucionó Claudio, la última liberación de CDPedia (0.8) es 
completamente funcional en windwos...
```

Original comment by `facundob...@gmail.com` on 25 Mar 2013 at 1:18
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
les quiero comentar que estube tratando de lanzar el cdpedia 0.8 tento en 
windows como en linux pero no tube exito primero lo quise ejecutar en win7 pero 
no respondio; luego me loguee en debian con la distibucion wayra haciendo doble 
clic en el fichero cdpedia.py sin exito; luego trate de hacerlo por la terminal 
con /media/PENDRIVE/cdpedia$ python cdpedia.py y me tiro el siguiente error: 
Traceback (most recent call last):
  File "cdpedia.py", line 50, in <module>
    from src import third_party # Need this to import thirdparty (werkzeug and jinja2)
ImportError: cannot import name third_party.

podrian ayudarme? o mandarme una version sin bug del fichero cdpedia.py.
desde ya muchas gracias.
Saludos cordiales



```

Original comment by `producci...@gmail.com` on 21 Aug 2013 at 3:01

**Comment by GoogleCodeExporter** [comment]
```
Para el problema en windows creé un issue separado con algunas sugerencias y 
algunas preguntas, por favor continua alli : issue 161, 
http://code.google.com/p/cdpedia/issues/detail?id=161.

Para el problema en linux, por favor crea tu mismo un issue separado.

Este issue es mas bien para empaquetado en windows.
```

Original comment by `ccanepacc@gmail.com` on 21 Aug 2013 at 2:29
