### ISSUE TITLE
Error "Too many open files" en el server web

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/cdpedia#158]
```
Reportado por un tercero en la lista:

"""
Les escribo también pues me aparece muy a menudo este error y no se como 
solucionarlo. A veces cierro el navegador y espero un rato y se soluciona, 
otras no, pero pasa muy a menudo y la verdad, fastidia bastante, con la version 
0.7 también me pasaba algo parecido. 

IOError

IOError: [Errno 24] Too many open files: 
'cdpedia\\src\\web\\templates\\500.html'
Traceback (most recent call last)

    File "C:\Users\Muskillo\Desktop\cdpedia-0.8-dvd5\cdpedia\src\third_party\werkzeug\wsgi.py", line 409, in __call__
    File "C:\Users\Muskillo\Desktop\cdpedia-0.8-dvd5\cdpedia\src\web\web_app.py", line 285, in wsgi_app
    File "C:\Users\Muskillo\Desktop\cdpedia-0.8-dvd5\cdpedia\src\web\web_app.py", line 277, in dispatch_request
    File "C:\Users\Muskillo\Desktop\cdpedia-0.8-dvd5\cdpedia\src\web\web_app.py", line 262, in render_template
    File "C:\Users\Muskillo\Desktop\cdpedia-0.8-dvd5\cdpedia\src\third_party\jinja2\environment.py", line 719, in get_template
    File "C:\Users\Muskillo\Desktop\cdpedia-0.8-dvd5\cdpedia\src\third_party\jinja2\environment.py", line 693, in _load_template
    File "C:\Users\Muskillo\Desktop\cdpedia-0.8-dvd5\cdpedia\src\third_party\jinja2\loaders.py", line 115, in load
    File "C:\Users\Muskillo\Desktop\cdpedia-0.8-dvd5\cdpedia\src\third_party\jinja2\loaders.py", line 165, in get_source
    File "C:\Users\Muskillo\Desktop\cdpedia-0.8-dvd5\cdpedia\src\third_party\jinja2\utils.py", line 224, in open_if_exists

    IOError: [Errno 24] Too many open files: 'cdpedia\\src\\web\\templates\\500.html'
"""
```

Original issue reported on code.google.com by `facundob...@gmail.com` on 22 Jan 2013 at 7:49

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```

Uso solo una maquina y la uso desde la misma maquina y lanzo la aplicación 
desde cdpedia.exe. Uso windows 7 64 bits con 12 gb de ram. La maquina es muy 
rápida Intel Core 7 960 a 3200 Mhz y tarjeta grafica dedicada de 1Gb de ram. 
El disco duro es SSD. Creo que el problema puede ser el que usted me comenta de 
las 512 files para apps de límite. ¿con qué aplicación puedo aumentar ese 
límite hasta el máximo?, no se como hacerlo. Por cierto, algo parecido me 
ocurría con la version 0.7 de Cdpedia
```

Original comment by `jmarand...@gmail.com` on 23 Jan 2013 at 12:00

**Comment by GoogleCodeExporter** [comment]
```
Actualizo, en la versión de linux que uso con una maquina virtual hay una 
solución al problema, pero es un coñazo, ya que tienes que tener una maquina 
virtual sobre windows con el problema del espacio en el disco duro. Está en 
ingles, pero se entiende bien con un ingles básico:

 OSB and Ubuntu 10.04 - Too Many Open Files
By user743649 on Feb 09, 2011

When installing the latest Oracle Service Bus (11gR1PS3) onto my Ubuntu 10.04 
system, the Eclipse IDE was complaining about there being too many open files. 
The Oracle Service Bus and the Oracle Enterprise Pack for Eclipse (aka OEPE) do 
make use of ALOT of files. By default, Ubuntu will restrict each user to 1024 
open files. A much more realistic number for OSB development is 4096.

Changing the file limit in Ubuntu is fairly simple (if arcane). You will need 
to modify two different files and then restart your server. First, you need to 
modify the limits.conf file as the root user. Open a terminal window and enter 
the following command:

sudo gedit /etc/security/limits.conf

Add the following 2 lines to the file. The asterisk simply means that the rule 
will apply to all users.

* soft nofile 4096
* hard nofile 4096

Save your changes and close gedit.

The second file to change is the common-session file. Use the following command:

sudo gedit /etc/pam.d/common-session

Add the following line:

session required pam_limits.so

Save the file and exit gedit. Restart your machine. You shouldn't have any more 
problems with too many open files anymore.

```

Original comment by `jmarand...@gmail.com` on 15 Feb 2013 at 10:30

**Comment by GoogleCodeExporter** [comment]
```
Fix commited on r405
```

Original comment by `facundob...@gmail.com` on 27 Dec 2013 at 4:59
- Changed state: **Fixed**
