### ISSUE TITLE
No funciona el botón de "Listado completo"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/cdpedia#22]
```
Cuando le das click al botón de "Listado completo" te tira lo siguiente:


Exception happened during processing of request from ('127.0.0.1', 43640)
Traceback (most recent call last):
  File "/usr/lib/python2.5/SocketServer.py", line 222, in handle_request
    self.process_request(request, client_address)
  File "/usr/lib/python2.5/SocketServer.py", line 241, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.5/SocketServer.py", line 254, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.5/SocketServer.py", line 522, in __init__
    self.handle()
  File "/usr/lib/python2.5/BaseHTTPServer.py", line 316, in handle
    self.handle_one_request()
  File "/usr/lib/python2.5/BaseHTTPServer.py", line 310, in handle_one_request
    method()
  File "/home/miya/workspace/cdpedia/src/src/armado/server.py", line 83, in
do_GET
    tipo, data = self.getfile(self.path)
  File "/home/miya/workspace/cdpedia/src/src/armado/server.py", line 138,
in getfile
    return self.listfull(query)
  File "/home/miya/workspace/cdpedia/src/src/armado/server.py", line 179,
in listfull
    articulos = self.index.listado_completo()
AttributeError: 'Index' object has no attribute 'listado_completo'


Se adjunta un patch que, por lo menos a mi, me funcionó.


```

Original issue reported on code.google.com by `nmiyas...@gmail.com` on 21 Mar 2009 at 10:47

Attachments:
- [lstCompleto.patch](https://storage.googleapis.com/google-code-attachments/cdpedia/issue-22/comment-0/lstCompleto.patch)

**Comment by GoogleCodeExporter** [comment]
Original comment by `facundob...@gmail.com` on 18 Jun 2009 at 1:38
- Added labels: **Milestone-Alpha1**

**Comment by GoogleCodeExporter** [comment]
```
Esto se arregló en algún momento...
```

Original comment by `facundob...@gmail.com` on 16 Jul 2009 at 1:34
- Changed state: **Fixed**
