### ISSUE TITLE
main.py debería probar otros puertos en caso de que el default esté ocupado

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/cdpedia#51]
```
En caso de que el puerto esté ocupado, ej.:

$ ./main.py
Levantando el server...
Traceback (most recent call last):
  File "./main.py", line 16, in <module>
    server.run(event)
  File "/home/pablo/CDPedia-CD-0.6/cdpedia/src/armado/server.py", line 323,
in run
    httpd = BaseHTTPServer.HTTPServer(('', 8000), WikiHTTPRequestHandler)
  File "/usr/lib/python2.6/SocketServer.py", line 400, in __init__
    self.server_bind()
  File "/usr/lib/python2.6/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.6/SocketServer.py", line 411, in server_bind
    self.socket.bind(self.server_address)
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use
```

Original issue reported on code.google.com by `pab...@gmail.com` on 25 Jan 2010 at 7:57

**Comment by GoogleCodeExporter** [comment]
```
Mejor aún: en caso de que el puerto esté usado, debería probar con otros!

Cambio el summary del bug para que refleje esto (creo que la idea original del 
OP no
es poder especificar puerto por flexibilidad, sino porque el otro está 
tomado... con
que sea dinámico alcanza)
```

Original comment by `facundob...@gmail.com` on 26 Jan 2010 at 12:20
- Changed title: **main.py debería probar otros puertos en caso de que el default esté ocupado**
- Changed state: **Accepted**
- Added labels: **Milestone-0.7**

**Comment by GoogleCodeExporter** [comment]
Original comment by `facundob...@gmail.com` on 26 Jan 2010 at 12:20
- Added labels: **Priority-High**

**Comment by GoogleCodeExporter** [comment]
```
Implementado en r200.
```

Original comment by `facundob...@gmail.com` on 18 Mar 2010 at 11:49
- Changed state: **Fixed**
