### ISSUE TITLE
main.py queda colgado si falla en el inicio

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/cdpedia#52]
```
ej.:

$ ./main.py
Levantando el server...
Traceback (most recent call last):
  File "./main.py", line 16, in <module>
    server.run(event)
  File "/home/pablo/CDPedia-CD-0.6/cdpedia/src/armado/server.py", line 323,
in run
    httpd = BaseHTTPServer.HTTPServer(('', 8000), WikiHTTPRequestHandler)
  File "/usr/lib/python2.6/SocketServer.py", line 400, in __init__
    self.server_bind()
  File "/usr/lib/python2.6/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.6/SocketServer.py", line 411, in server_bind
    self.socket.bind(self.server_address)
  File "<string>", line 1, in bind
socket.error: [Errno 98] Address already in use


^C
^C
^C

La consola quedó inutilizable después de eso. Es más grave si uno en vez de
usar la consola hace doble click en el ícono porque no obtiene ningún tipo
de feedback
```

Original issue reported on code.google.com by `pab...@gmail.com` on 25 Jan 2010 at 8:02

**Comment by GoogleCodeExporter** [comment]
```
Este error nunca debería sucederse (ver issue 51).

Cierro esto como inválido, pero si hay otro bug que haga dejar colgado esto, 
lo vemos.

Gracias!!
```

Original comment by `facundob...@gmail.com` on 26 Jan 2010 at 12:15
- Changed state: **Invalid**
